// Table Data
const TableData = [
  {
      id: 1,
      profile: "assets/img/contact/01.png",
      name: "David Millar",
      designation: "(CEO)*",
      company: "ReacThemes",
      phone: "+8801265648289",
      email: "millar@mail.com",
  },
  {
    id: 2,
    profile: "assets/img/contact/02.png",
    name: "Brian Pfeffer",
    designation: "Senior Developer",
    company: "pixeluniverce",
    phone: "+880121238789",
    email: "Brian@mail.com",
  },
  {
    id: 3,
    profile: "assets/img/contact/03.png",
    name: "Tamim Iqbal",
    designation: "Developer",
    company: "ReacThemes",
    phone: "+880125968789",
    email: "Tamim@mail.com",
  },
  {
    id: 4,
    profile: "assets/img/contact/04.png",
    name: "Mehadi Meraj",
    designation: "Senior Designer",
    company: "pixeluniverce",
    phone: "+880123235419",
    email: "Mehadi@mail.com",
  },
  {
    id: 5,
    profile: "assets/img/contact/05.png",
    name: "Sakib Al Hasan",
    designation: "Designer",
    company: "ReacThemes",
    phone: "+880123464239",
    email: "Sakib@mail.com",
  },
  {
    id: 6,
    profile: "assets/img/contact/06.png",
    name: "MR.John Lee",
    designation: "Content Writer",
    company: "pixeluniverce",
    phone: "+880123456889",
    email: "John@mail.com",
  },
  {
    id: 7,
    profile: "assets/img/contact/07.png",
    name: "Christopher",
    designation: "(COO)",
    company: "ReacThemes",
    phone: "+880123468789",
    email: "Christopher@mail.com",
  },
  {
    id: 8,
    profile: "assets/img/contact/08.png",
    name: "MR.Christopher",
    designation: "Central Usability Officer",
    company: "pixeluniverce",
    phone: "+880123468789",
    email: "Christopher@mail.com",
  },
];

export { TableData };
