// File Data
const FileData = [
  {
      id: 1,
      image: "assets/img/file/06.png",
      name: "Main Proposal Documents",
      items: "24",
      time: "20",
      size: "24,476",
  },
  {
    id: 2,
    image: "assets/img/file/04.png",
    name: "EnglishLesson1.Mp3",
    items: "24",
    time: "20",
    size: "24,476",
  },
  {
    id: 3,
    image: "assets/img/file/03.png",
    name: "Take-A-Look-My-Garden.Mp4",
    items: "24",
    time: "20",
    size: "24,476",
  },
  {
    id: 4,
    image: "assets/img/file/05.png",
    name: "Mobile-Photo.Pdf",
    items: "24",
    time: "20",
    size: "24,476",
  },
  {
    id: 5,
    image: "assets/img/file/02.png",
    name: "Image_bg.Jpeg",
    items: "24",
    time: "20",
    size: "24,476",
  },
  {
    id: 6,
    image: "assets/img/file/04.png",
    name: "EnglishLesson1.Mp3",
    items: "24",
    time: "20",
    size: "24,476",
  },
  {
    id: 7,
    image: "assets/img/file/03.png",
    name: "Take-A-Look-My-Garden.Mp4",
    items: "24",
    time: "20",
    size: "24,476",
  },
  {
    id: 8,
    image: "assets/img/file/05.png",
    name: "Mobile.Pdf",
    items: "24",
    time: "20",
    size: "24,476",
  },
  {
    id: 9,
    image: "assets/img/file/02.png",
    name: "Wash-Hand.Jpeg",
    items: "24",
    time: "20",
    size: "24,476",
  },
];

export { FileData };
