// History Data
const HistoryData = [
  {
      id: 1,
      icon: "uil uil-arrow-down",
      type: "decrement",
      title: "Paypal Transfer",
      time: "November 24th, 2020 at 2:45 AM",
      img: "assets/img/avatar/t1.svg",
      name: "Thomas Edison",
      sub_title: "@thomasedis",
      price: "$98.21",
      price_type: "decrement",
  },
  {
    id: 2,
    icon: "uil uil-arrow-down",
    type: "decrement",
    title: "Upgrade Storage Plan",
    time: "November 24th, 2020 at 2:45 AM",
    img: "assets/img/icon/dropbox.svg",
    name: "Dropbox",
    sub_title: "November",
    price: "$200",
    price_type: "increment",
  },
  {
    id: 3,
    icon: "uil uil-arrow-up",
    type: "increment",
    title: "Bank Transfer",
    time: "September 5th, 2020 at 11:56 AM",
    img: "assets/img/avatar/t2.svg",
    name: "Louis Khun",
    sub_title: "@thomasedis",
    price: "$500",
    price_type: "increment",
  },
  {
    id: 4,
    icon: "uil uil-arrow-down",
    type: "decrement",
    title: "Youtube Monthly Subcrition",
    time: "September 5th, 2020 at 11:56 AM",
    img: "assets/img/icon/youtube.svg",
    name: "Youtube",
    sub_title: "September",
    price: "$200",
    price_type: "decrement",
  },
  {
    id: 5,
    icon: "uil uil-arrow-up",
    type: "increment",
    title: "Bank Transfer",
    time: "September 5th, 2020 at 11:56 AM",
    img: "assets/img/avatar/t3.svg",
    name: "Isabella Sirait",
    sub_title: "@thomasedis",
    price: "$500",
    price_type: "increment",
  },
];

export { HistoryData };
